export { lint, type LintResult } from './linter.js'
export { loadConfig } from './config/loader.js'
export { type DepsLintConfig, type DepsLintPackageConfig } from './config/types.js'
export { type Diagnostic, type DiagnosticType, type CheckContext } from './checks/types.js'
export { formatText, formatJson } from './output/formatter.js'
export { applyFixes, isFixable, type FixAction, type FixResult } from './fixer.js'
export { type Rule, type PackageRule, type WorkspaceRule, type FixContext } from './checks/rule.js'
export { allRules, packageRules, workspaceRules } from './checks/rules/index.js'
